spring.application.name=demo
server.port=8080
management.endpoint.shutdown.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/stsdemo
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
spring.cloud.config.import-check.enabled=false

#New way to import config server properties
spring.config.import=configserver:
spring.profiles.active=production
# /actuator/health /actuator/refresh Such endpoints will be exposed
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.metrics.export.prometheus.enabled=true
