spring.application.name=configserver
# Server port
server.port=8888

# Git repo location
spring.cloud.config.server.git.uri=file:///C:/Spring boot-cloud-microservice/config-server-repo
spring.cloud.config.server.git.clone-on-start=true

# Disable security of the Management endpoint
management.endpoints.web.exposure.include=*